name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
         with:
aws-access-key-id:  ${{ secrets.MY_AWS_ACCESS_KEY}}
aws-secret-access-key:  ${{ secrets.MY_SECRET_KEY}}
aws-region: "us-east-1"

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan
      
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: terraform
  steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
   deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

